version: '3'
services:
  mysql8.0:
    image: mysql:8.0
    container_name: movie_db
    ports:
      - 3380:3306
    environment:
      - MYSQL_DATABASE=${MOVIE_DB_NAME}
      - MYSQL_USER=${MOVIE_DB_USER}
      - MYSQL_PASSWORD=${MOVIE_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MOVIE_DB_ROOT_PASSWORD}
