version: '3'
services:
  postgres:
    container_name: people_db
    image: postgres:14-alpine3.15
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${PEOPLE_DB_PASSWORD}
      POSTGRES_USER: ${PEOPLE_DB_USERNAME}
      POSTGRES_DB: ${PEOPLE_DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
